// <auto-generated />
using System;
using DigLabAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigLabAPI.Migrations
{
    [DbContext(typeof(DigLabDb))]
    [Migration("20250909194824_SeedPersonsAndOrders")]
    partial class SeedPersonsAndOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DigLabAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DiagnosesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Personnummer")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("LabNumber")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 379, DateTimeKind.Utc).AddTicks(9692),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Dengue\"]",
                            LabNumber = "LAB-20250909-AAA11111",
                            Name = "Ola Nordmann",
                            Personnummer = "01010112345",
                            Time = new TimeOnly(9, 15, 0)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 379, DateTimeKind.Utc).AddTicks(9985),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Malaria\"]",
                            LabNumber = "LAB-20250909-BBB22222",
                            Name = "Kari Nordmann",
                            Personnummer = "02020223456",
                            Time = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 379, DateTimeKind.Utc).AddTicks(9987),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"TBE\",\"Dengue\"]",
                            LabNumber = "LAB-20250909-CCC33333",
                            Name = "Per Hansen",
                            Personnummer = "03030334567",
                            Time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 379, DateTimeKind.Utc).AddTicks(9989),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Hantavirus – Puumalavirus (PuV)\"]",
                            LabNumber = "LAB-20250909-DDD44444",
                            Name = "Anne Larsen",
                            Personnummer = "04040445678",
                            Time = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 379, DateTimeKind.Utc).AddTicks(9991),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Dengue\"]",
                            LabNumber = "LAB-20250909-EEE55555",
                            Name = "Marius Bakke",
                            Personnummer = "05050556789",
                            Time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 379, DateTimeKind.Utc).AddTicks(9992),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Malaria\",\"TBE\"]",
                            LabNumber = "LAB-20250909-FFF66666",
                            Name = "Ingrid Lie",
                            Personnummer = "06060667890",
                            Time = new TimeOnly(11, 15, 0)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 379, DateTimeKind.Utc).AddTicks(9994),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"TBE\"]",
                            LabNumber = "LAB-20250909-GGG77777",
                            Name = "Jonas Moen",
                            Personnummer = "07070778901",
                            Time = new TimeOnly(11, 45, 0)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 380, DateTimeKind.Utc).AddTicks(65),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Dengue\",\"Malaria\"]",
                            LabNumber = "LAB-20250909-HHH88888",
                            Name = "Camilla Johansen",
                            Personnummer = "08080889012",
                            Time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 380, DateTimeKind.Utc).AddTicks(66),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Hantavirus – Puumalavirus (PuV)\"]",
                            LabNumber = "LAB-20250909-III99999",
                            Name = "Andreas Solheim",
                            Personnummer = "09090990123",
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 380, DateTimeKind.Utc).AddTicks(68),
                            Date = new DateOnly(2025, 9, 9),
                            DiagnosesJson = "[\"Malaria\"]",
                            LabNumber = "LAB-20250909-JJJ00000",
                            Name = "Sofie Berg",
                            Personnummer = "10101001234",
                            Time = new TimeOnly(13, 0, 0)
                        });
                });

            modelBuilder.Entity("DigLabAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Personnummer")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "Storgata 1",
                            City = "Oslo",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7415),
                            Email = "ola@example.com",
                            FirstName = "Ola",
                            LastName = "Nordmann",
                            Personnummer = "01010112345",
                            Phone = "90000001",
                            PostalCode = "0001"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "Parkveien 22",
                            City = "Bergen",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7731),
                            Email = "kari@example.com",
                            FirstName = "Kari",
                            LastName = "Nordmann",
                            Personnummer = "02020223456",
                            Phone = "90000002",
                            PostalCode = "5003"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "Markveien 12",
                            City = "Trondheim",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7733),
                            Email = "per@example.com",
                            FirstName = "Per",
                            LastName = "Hansen",
                            Personnummer = "03030334567",
                            Phone = "90000003",
                            PostalCode = "7010"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine1 = "Solbergveien 7",
                            City = "Tromsø",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7735),
                            Email = "anne@example.com",
                            FirstName = "Anne",
                            LastName = "Larsen",
                            Personnummer = "04040445678",
                            Phone = "90000004",
                            PostalCode = "9008"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine1 = "Skogveien 14",
                            City = "Gjøvik",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7737),
                            Email = "marius@example.com",
                            FirstName = "Marius",
                            LastName = "Bakke",
                            Personnummer = "05050556789",
                            Phone = "90000005",
                            PostalCode = "2815"
                        },
                        new
                        {
                            Id = 6,
                            AddressLine1 = "Havnegata 3",
                            City = "Fredrikstad",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7739),
                            Email = "ingrid@example.com",
                            FirstName = "Ingrid",
                            LastName = "Lie",
                            Personnummer = "06060667890",
                            Phone = "90000006",
                            PostalCode = "1606"
                        },
                        new
                        {
                            Id = 7,
                            AddressLine1 = "Kirkeveien 15",
                            City = "Lillestrøm",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7740),
                            Email = "jonas@example.com",
                            FirstName = "Jonas",
                            LastName = "Moen",
                            Personnummer = "07070778901",
                            Phone = "90000007",
                            PostalCode = "2004"
                        },
                        new
                        {
                            Id = 8,
                            AddressLine1 = "Elveveien 2",
                            City = "Stavanger",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7742),
                            Email = "camilla@example.com",
                            FirstName = "Camilla",
                            LastName = "Johansen",
                            Personnummer = "08080889012",
                            Phone = "90000008",
                            PostalCode = "4005"
                        },
                        new
                        {
                            Id = 9,
                            AddressLine1 = "Fjordgata 9",
                            City = "Molde",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7744),
                            Email = "andreas@example.com",
                            FirstName = "Andreas",
                            LastName = "Solheim",
                            Personnummer = "09090990123",
                            Phone = "90000009",
                            PostalCode = "6411"
                        },
                        new
                        {
                            Id = 10,
                            AddressLine1 = "Torget 8",
                            City = "Hamar",
                            CreatedAtUtc = new DateTime(2025, 9, 9, 19, 48, 24, 378, DateTimeKind.Utc).AddTicks(7745),
                            Email = "sofie@example.com",
                            FirstName = "Sofie",
                            LastName = "Berg",
                            Personnummer = "10101001234",
                            Phone = "90000010",
                            PostalCode = "2317"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
